FROM python:3.11-slim-buster

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /opt/app

ENV PYTHONPATH="/opt/app:${PYTHONPATH}"

COPY ./web_dashboard/requirements-dash.txt .
RUN pip install --no-cache-dir -r requirements-app.txt

COPY ./app ./app 
COPY ./configs ./configs

COPY ./web_dashboard ./web_dashboard

EXPOSE 8050
CMD ["python", "web_dashboard/app.py"]