x-app-image-name: &app-image "niejemglutenu/trading_platform_app:latest"

x-cli-app-base: &cli-app-base
  env_file: .env
  build:
    context: .
    dockerfile: Dockerfile 
  volumes:
    - ./app:/opt/app/app   
    - ./configs:/opt/app/configs 
    - ./data:/opt/app/data 
    - ./logs:/opt/app/logs   
    - ./data/matplotlib_cache:/opt/app/data/matplotlib_cache
  environment:
  - PYTHONUNBUFFERED=1
  - MPLCONFIGDIR=/opt/app/data/matplotlib_cache
  - DB_HOST=host.docker.internal      
  - DB_NAME=${DB_NAME_ENV_VAR}
  - DB_USER=${DB_USER_ENV_VAR}
  - DB_PASSWORD=${DB_PASSWORD_ENV_VAR}
  - ALPACA_API_KEY=${ALPACA_API_KEY_ENV_VAR}
  - ALPACA_API_SECRET=${ALPACA_API_SECRET_ENV_VAR}
  - ALPACA_SANDBOX_MODE=${ALPACA_SANDBOX_MODE_ENV_VAR}
  
  develop: 
    watch:
      - action: sync 
        path: ./app 
        target: /opt/app/app 
        ignore: 
          - __pycache__/
          - .git/
          - .venv/ 
      - action: rebuild 
        path: requirements.txt

  


services:
  backtest-runner:
    <<: *cli-app-base 
    container_name: trading_platform_backtester
    command: > 
      python -m app.cli
      --mode "backtest" 
      --base-config "app_config.yaml"
      --profile-config "app_config.yaml" 
    volumes:
      - ./app:/opt/app/app
      - ./configs:/opt/app/configs
      - ./data:/opt/app/data:rw
      - ./logs:/opt/app/logs:rw
      - ./data/matplotlib_cache:/opt/app/data/matplotlib_cache:rw
    environment:
      - PYTHONUNBUFFERED=1
      - MPLCONFIGDIR=/opt/app/data/matplotlib_cache
      - DB_HOST=host.docker.internal
      - DB_NAME=${DB_NAME_ENV_VAR}
      - DB_USER=${DB_USER_ENV_VAR}
      - DB_PASSWORD=${DB_PASSWORD_ENV_VAR}
      - ALPACA_API_KEY=${ALPACA_API_KEY_ENV_VAR}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET_ENV_VAR}
      - ALPACA_SANDBOX_MODE=${ALPACA_SANDBOX_MODE_ENV_VAR}
      - DATA_DIR=/opt/app/data  
    restart: "no"

  